### ISSUE TITLE
Возможность поставить пользователю статус «Преподаватель»

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.edu#10]
Добавить в профиль пользователя кнопку «Активировать статус преподавателя», которая будет добавлять/убирать статус преподавателя.

В профиле сделать вывод бэйджа «Преподаватель» рядом с аватаркой. Можно пока просто текстом.

**Comment by illiiiillllilii** [comment]
Возникни небольшие проблемы с версткой и css
Добавил пока просто надпись рядом с именем.

Ссылки на соц.сети лучше сделать в виде кнопок

**Comment by neSpecc** [comment]
скриншот?

**Comment by illiiiillllilii** [comment]
Шрифт темный на тёмном фоне. И я не знаю, как добавить этикетку, кроме как в тег к имени, где в css сказано, что шрифт будет светлым
Виталя [преподаватель]

**Comment by illiiiillllilii** [comment]
Кнопки "активировать статус преподавателя" есть

**Comment by neSpecc** [comment]
все норм. Дизайн сделаем, не проблема

**Comment by illiiiillllilii** [comment]
<img width="1198" alt="screen shot 2015-12-11 at 17 46 14" src="https://cloud.githubusercontent.com/assets/15259299/11746413/21ddd9de-a02f-11e5-8dc2-6f6859d22a1b.png">
