### ISSUE TITLE
Трансляция новостей в паблик ВК

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.edu#119]
1) Кнопка для админов «Подключить группу ВКонтакте»
2) В форме добавления новости добавить флаг "[ ] транляция в вк"
2) При публикации новостей автоматически транслировать их в группу ВК, если выбран флаг

Для теста надо создать новую группу

**Comment by talyguryn** [comment]
## Методы и необходимые параметры

Создаем пост в группе методом [wall.post](https://vk.com/dev/wall.post) и в ответ получаем либо ошибку, либо id созданного поста.
- access_token
- owner_id
- message
- from_group

Редактируем пост методом [wall.edit](https://vk.com/dev/wall.edit).
- access_token
- owner_id
- post_id
- message

Удаляем пост методом [wall.delete](https://vk.com/dev/wall.delete).
- access_token
- owner_id
- post_id
