### ISSUE TITLE
Раздел "фотографии" в странице

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.edu#120]

**Comment by neSpecc** [comment]
- [ ] добавить кнопку «прикрепить изображение» в форме
- [ ] должна быть возможность выбора нескольких файлов одновременно
- [ ] сразу все фотки залить не получится из-за ограничений на размер и время запроса, поэтому надо реализовать заливку их по очереди, можно сделать красивый попап с прогрессом загрузки каждой фотографии
- [ ] вывод изображений на странице в виде красивой сетки из миниатюр, но не очень маленьких
### Дополнительно
- [ ] Реализовать предварительное сжатие изображения на клиенте через canvas.
Это существенно увеличит скорость загрузки пачки картинок и стабильность работы

**Comment by neSpecc** [comment]
- [ ] добавить в форму кнопку добавления картинки (в шрифте есть иконка)
- [ ] сделать, чтобы скрипт различал загрузку картинок и файлов (функция codex.transport.selectFile вторым параметром принимает тип — сейчас Controller_Transport::PAGE_FILE, надо еще сделать Controller_Transport::PAGE_IMAGE )
- [ ] внести изменения в фукнцию fileSelected, которая срабатывает сразу после выбора файлов: сейчас она просто отправляет выбранный файл. Тебе надо, чтобы, если выбрано несколько файлов, она:
    1. [ ] показывала попап со списком выбранных файлов
    2. [ ] начинала загрузку первого файла и ждала ответа
    3. [ ] после загрузки файла записывала его имя в codex.transport.images (по аналогии с codex.transport.files) — можно сделать функцию storeImage по аналогии со storeFile или дописать вторую, чтобы учитывала тип
    4. [ ] после этого начинала загружать следующий
- [ ] отправка  codex.transport.images вместе с формой
- [ ] сохранение изображений в базу 
- [ ] вывод изображений на странице
