### ISSUE TITLE
Страница настроек сайта

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.edu#13]
Создать страницу настроек сайта в панели управления

* Название сайта
* Краткое описание
* Логотип
* Почта
* Телефон
* Адрес

Настройки будут добавляться.

**Comment by neSpecc** [comment]
Храть их можно в базе

**Comment by illiiiillllilii** [comment]
Сразу делаем универсальную платформу?

**Comment by neSpecc** [comment]
не понял вопроса

**Comment by illiiiillllilii** [comment]
Избавляемся от статичного отображения информации и берём данные из бд
Все понял

**Comment by neSpecc** [comment]
Я на тебя тогда задачу поставлю

**Comment by illiiiillllilii** [comment]
Задаем глобальную переменную в предиспаче и заполняем ее.
```php
View::set_global('site_info', $this->methods->getSiteInfo());
```
Значение должны быть примерно такими
```php
public function getSiteInfo(){

        $this->title        = '332&nbsp;школа<br>Санкт-Петербруга';
        $this->full_name    = 'ГБОУ&nbsp;СОШ&nbsp;№332 Невского&nbsp;района';
        $this->description  = '';

        $this->address  = '193312&nbsp;Санкт-Петербург, Товарищеский&nbsp;пр.,&nbsp;д.&nbsp;10,&nbsp;корп.&nbsp;2';
        $this->phone    = '580-89-08;&nbsp;584-54-98';
        $this->fax      = '580-82-49';
        $this->email    = 'spb_school332@mail.ru';

        $this->logo     = '';

        return $this;
    }
```

И выводим все main.php
```html
<footer class="site_footer">
    <p><?= $site_info->full_name ?></p>
    <p>
        <a href="/contacts">
            <?= $site_info->address ?>
        </a>
    </p>
    <p>
        Телефон:&nbsp;<?= $site_info->phone ?><br />
        Факс:&nbsp;<?= $site_info->fax ?><br />
        Почта:&nbsp;<?= $site_info->email ?>
    </p>
</footer>
```

**Comment by illiiiillllilii** [comment]
Работа с бд есть
Создаю страницу настроек

**Comment by illiiiillllilii** [comment]
Лучше взять таблицу из трех столбцов: variable, title, value.
Чтобы иметь возможность редактировать пункты настроек
Что-то подобное:
```php
['title', 'Заголовок', '332 школа<br>Санкт-Петербурга']
['phone', 'Телефон', '580-89-08;&nbsp;584-54-98']
...
```

**Comment by illiiiillllilii** [comment]
Форма сделана, работает.

<img width="501" alt="screen shot 2015-12-11 at 14 07 31" src="https://cloud.githubusercontent.com/assets/15259299/11742383/90dc1f9a-a010-11e5-8432-a705d641de50.png">

**Comment by illiiiillllilii** [comment]
- [ ] sdks

**Comment by illiiiillllilii** [comment]
Новые квесты:
- [ ] выбрать вид таблицы в бд для хранения информации (вертикальная или горизонтальная)
- [ ] сверстать форму
- [ ] сделать проверку на осознание значимости изменений этих данных (возможно с подтверждением через почту)

**Comment by neSpecc** [comment]
классы для оформления формы можешь взять из админки

**Comment by illiiiillllilii** [comment]
При сохранении настройки будут записываться в новую строку таблицы, дабы избежать потере данных при отправке неправильно заполненной формы. Нужно иметь возможность откатиться
