### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by illiiiillllilii** [codex-team/codex.edu#16]
Необходимо разработать удобную и функциональную часть сайта для управления контентом, комментариями и пользователями.
Также необходимо представить наглядно всю статистику по сайту - посещения и просмотры страниц, фидбек, а также активность пользователей.

Все предложения по расширению функциональности дашборда принимаются

**Comment by illiiiillllilii** [comment]
- [ ] вынести "быстрые действия из панени управления" и разместить их в левом столбце

**Comment by neSpecc** [comment]
предлагаю разнести это на несколько задач. По каждому разделу
