### ISSUE TITLE
Добавить возможность установить брендированную подложку в шапку (админам)

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.edu#163]
![image](https://cloud.githubusercontent.com/assets/3684889/23621233/e02a97b8-02aa-11e7-851b-17015af3b432.png)

**Comment by neSpecc** [comment]
Вопрос: как установить ее в первый раз? На странице настроек или добавить иконку сверху для админов?

**Comment by talyguryn** [comment]
Изначально оставить пустым блоком, как на макете.
Ну, и админам показывать кнопку "сменить изображение".
