### ISSUE TITLE
Заполнить сайт актуальной информацией

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.edu#172]
Необходимо создать страницы и вставить туда содержимое страниц старого сайта.
Дерево страниц и ссылки находятся в приложенном файле.

[glavnoe_menyu_sayta.pdf](https://github.com/codex-team/codex.edu/files/831821/glavnoe_menyu_sayta.pdf)

**Comment by neSpecc** [comment]
Важно при этом обеспечить хороший внешний вид материалов: убрать из них жирность, курсив и прочий мусор,  проверить разделение на абзацы и тд

**Comment by talyguryn** [comment]
перенесено в #317
