### ISSUE TITLE
Сверстать страницу настроек пользователя user/settings

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.edu#176]
И добавить ссылку на эту страницу в профиль

**Comment by talyguryn** [comment]
![profile](https://cloud.githubusercontent.com/assets/15259299/23792377/b866fe34-0597-11e7-87f0-22d53e6e02d8.png)

**Comment by talyguryn** [comment]
![profilesettings](https://cloud.githubusercontent.com/assets/15259299/23831268/0128df96-072f-11e7-8f87-c8e23255d467.png)

**Comment by neSpecc** [comment]
![image](https://cloud.githubusercontent.com/assets/3684889/23960383/e572195c-09b8-11e7-8bb0-c96ceecff649.png)
