### ISSUE TITLE
Настроить почтовый сервер

### ISSUE THREAD

**Issue by gohabereg** [codex-team/codex.edu#185]
Для начала, поднять.
Изучить, что и как настроить для корректной отправки писем (DNS-зоны, PTR и SPF)

**Comment by talyguryn** [comment]
http://gansik.ru/ubuntu/php-mail-i-ssmtp/

**Comment by talyguryn** [comment]
копия статьи по поднятию на сервере возможности отправки почтовых нотификаций (с ссылкой на оригинал) не помешает

**Comment by talyguryn** [comment]
https://habrahabr.ru/post/114852/

**Comment by neSpecc** [comment]
https://www.sparkpost.com/pricing/
