### ISSUE TITLE
Разработать дизайн блока scrollUp

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.edu#188]

**Comment by neSpecc** [comment]
Обычное состояние. Занимает всю высоту, ширина — 100px.

![image](https://cloud.githubusercontent.com/assets/3684889/23822885/264674e6-0667-11e7-8c1b-4d798b17e17c.png)


Ховер:

![image](https://cloud.githubusercontent.com/assets/3684889/23822917/da5385be-0667-11e7-8d67-9edfe752a2d7.png)

**Comment by neSpecc** [comment]
Еще пожелание: чтобы кликабельной была вся зона слева от левой колонки. То есть стрелка по ширине 100px, прижата к левому краю экрана, но зона ховера/клика была шире.

Тогда на широких мониторах не придется тащить курсор до стрелочки, а можно будет кликать в любое место слева.

![scrollup](https://cloud.githubusercontent.com/assets/3684889/23822974/014be20a-0669-11e7-942a-bf8948b21f4c.png)

**Comment by neSpecc** [comment]
[arrow-up.svg.zip](https://github.com/codex-team/codex.edu/files/835704/arrow-up.svg.zip)
