### ISSUE TITLE
Email confirmation design

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.edu#207]
Необходимо разработать дизайн и верстку письма.
Также надо добавить текстовую ссылку для копирования, если не работают ссылки в письме.
Заменить www-data на что-то более информативное "notification/noreply/bot/..."
<img width="681" alt="screen shot 2017-03-17 at 11 13 18" src="https://cloud.githubusercontent.com/assets/15259299/24034549/bc719f5a-0b02-11e7-96ea-6fb2d69ea670.png">

**Comment by neSpecc** [comment]
В первой версии будут plain-text письма. Но шаблоны к ним все равно надо проработать.

```plain
Здравствуйте, Виталя!

Вы запросили сброс пароля на gamma.ifmo.su. Чтобы установить новый пароль, перейдите по следующей ссылке:

[ссылка]

Если вы получили письмо по ошибке, можно ничего не делать.
```

**Comment by neSpecc** [comment]
@talyguryn займись оформлением писем в таком стиле: с разбивкой на абзацы

**Comment by talyguryn** [comment]
Принято
