### ISSUE TITLE
Разработать дизайн уведомлений

### ISSUE THREAD

**Issue by talyguryn** [codex-team/codex.edu#229]

**Comment by talyguryn** [comment]
![223021460_11654581471860314487](https://cloud.githubusercontent.com/assets/15259299/24586367/fcbd4242-17a7-11e7-9eb3-8cac774cfd30.jpg)

**Comment by neSpecc** [comment]
![image](https://cloud.githubusercontent.com/assets/3684889/24586374/10bb46c2-17a8-11e7-965e-6e11e04a3567.png)
