### ISSUE TITLE
Исправить алгоритм для создания uri страниц

### ISSUE THREAD

**Issue by illiiiillllilii** [codex-team/codex.edu#49]
Необходимо исправить алгоритм так, чтобы буквы и цифры сохранялись, а **все остальные** символы заменялись на дефисы.
Сейчас замена производится по строго заданному массиву соотношений.

**Comment by khaydarov** [comment]
Это случайно не то, что я делал в пятницу ?

**Comment by neSpecc** [comment]
тут имеется ввиду только функция транслитерации заголовка в uri

**Comment by illiiiillllilii** [comment]
@khaydarov 
Model_Methods::rus2translit($string)
