### ISSUE TITLE
Список пользователей

### ISSUE THREAD

**Issue by illiiiillllilii** [codex-team/codex.edu#50]
Необходимо организовать вывод списка учителей на определенной странице

Администраторы также будут выводиться в этом списке. Не стоит никак выделять их. Пользователям не стоит знать, кто обладает правами администратора.

**Comment by loopdigga98** [comment]
@illiiiillllilii на каком роуте это все будет висеть?

**Comment by neSpecc** [comment]
можно сделать например 
/users — список всех пользователей с пагинацией
/users/teachers — список учителей
