### ISSUE TITLE
Парсер для импорта страниц

### ISSUE THREAD

**Issue by illiiiillllilii** [codex-team/codex.edu#51]
При создании страницы можно импортировать **заголовок** и **тело статьи** с любого сайта по url

**Comment by illiiiillllilii** [comment]
Стоит поискать информацию о том, как браузеры формирует страницу "для чтения". Это может помочь в решении задачи.

Обычную страницу сайта
<img width="1210" alt="screen shot 2016-02-28 at 13 23 32" src="https://cloud.githubusercontent.com/assets/15259299/13378668/9e884050-de1e-11e5-915a-8cc5f8cf1c47.png">

Представляется в таком виде
<img width="1208" alt="screen shot 2016-02-28 at 13 23 39" src="https://cloud.githubusercontent.com/assets/15259299/13378672/a4044eac-de1e-11e5-8ed5-7c2d5c4dba93.png">

**Comment by neSpecc** [comment]
браузеру проще, потому что это клиент, он видит, как выглядит страница. 

Придумай что-нибудь.
