### ISSUE TITLE
Авторизация через соцсети

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.edu#7]
На основе созданной системы авторизации  `Controller_Auth_Base` реализовать авторизацию через соцсети
* vk.com
* Facebook
* Twitter

Роуты для авторизации через соцсети: 

`/auth/vk`
`/auth/facebook`
`/auth/twitter`

Можно отправить их в тот же экшен `Controller_Auth_Auth/action_auth` , и дописать там `case` под каждую соцсеть.

После успешной авторизации через соцсеть, должна инициализироваться наша авторизационная сессия  через `Conroller_Auth_Base::initAuthSession($uid, $socialProvider)`

Желательно, добавить возможность уже авторизованному пользователю привязать недостающие соцсети. В этом случае, `initAuthSession` вызывать не нужно. 

При авторизации через ВК дополнительно передавать `https=1` и запрашивать поле `email` (нет в документации)

**Comment by illiiiillllilii** [comment]
Как дела с задачей?

**Comment by demyashev** [comment]
Петя забыл закрыть
