### ISSUE TITLE
Страница настроек пользователя

### ISSUE THREAD

**Issue by neSpecc** [codex-team/codex.edu#8]
Страница `user/settings` со следующими возможностями:

- [x] Изменение фотографии
- [x] Смена почты
- [ ] Смена пароля
- [ ] Привязка/отвязка соцсетей
- [x] Кнопка логаута
- [ ] смена пароля с подтверждением по почте

**Comment by illiiiillllilii** [comment]
Учителю нужно будет добавить поле с номером телефона

**Comment by loopdigga98** [comment]
@neSpecc порешали же смену пароля в следующей задаче сделать.

**Comment by neSpecc** [comment]
Привязка/отвязка соцсетей делается в #52

**Comment by neSpecc** [comment]
на смену пароля сделал новую задачу #56
